/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalCareRouteImport } from './routes/professional-care'
import { Route as ApiAgeTransformRouteImport } from './routes/api.age-transform'
import { Route as ApiLeadCaptureRouteImport } from './routes/api.lead-capture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalCareRoute = ProfessionalCareRouteImport.update({
  id: '/professional-care',
  path: '/professional-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgeTransformRoute = ApiAgeTransformRouteImport.update({
  id: '/api/age-transform',
  path: '/api/age-transform',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadCaptureRoute = ApiLeadCaptureRouteImport.update({
  id: '/api/lead-capture',
  path: '/api/lead-capture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/professional-care': typeof ProfessionalCareRoute
  '/api/age-transform': typeof ApiAgeTransformRoute
  '/api/lead-capture': typeof ApiLeadCaptureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/professional-care': typeof ProfessionalCareRoute
  '/api/age-transform': typeof ApiAgeTransformRoute
  '/api/lead-capture': typeof ApiLeadCaptureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/professional-care': typeof ProfessionalCareRoute
  '/api/age-transform': typeof ApiAgeTransformRoute
  '/api/lead-capture': typeof ApiLeadCaptureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/professional-care' | '/api/age-transform' | '/api/lead-capture'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/professional-care' | '/api/age-transform' | '/api/lead-capture'
  id:
    | '__root__'
    | '/'
    | '/professional-care'
    | '/api/age-transform'
    | '/api/lead-capture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfessionalCareRoute: typeof ProfessionalCareRoute
  ApiAgeTransformRoute: typeof ApiAgeTransformRoute
  ApiLeadCaptureRoute: typeof ApiLeadCaptureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-care': {
      id: '/professional-care'
      path: '/professional-care'
      fullPath: '/professional-care'
      preLoaderRoute: typeof ProfessionalCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/age-transform': {
      id: '/api/age-transform'
      path: '/api/age-transform'
      fullPath: '/api/age-transform'
      preLoaderRoute: typeof ApiAgeTransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-capture': {
      id: '/api/lead-capture'
      path: '/api/lead-capture'
      fullPath: '/api/lead-capture'
      preLoaderRoute: typeof ApiLeadCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfessionalCareRoute: ProfessionalCareRoute,
  ApiAgeTransformRoute: ApiAgeTransformRoute,
  ApiLeadCaptureRoute: ApiLeadCaptureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
